# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 749c9c680039fcba9deee62d3e0512527de83869bf8a92d8376bda759dd71fd663cf5e706759cc356cbb415f02734fa0c6d1d4a59548a48371c98329c04de54e

test:
  secret_key_base: 2796ab1af4053b5afdff5d4341fda97dd5d4a0be4b972023b4a74651fcca3050397bd6c8465b634593f22cc9002ece81c4fd4438a2275040deb38423837b40ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
